version: "3"

services:
    database:
        image: postgres
        restart: on-failure
        environment:
            POSTGRES_USER: '${DATABASE_USER}'
            POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
            POSTGRES_DB: '${DATABASE_NAME}'
        volumes:
            - data:/var/lib/postgresql/data
    api:
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile
            target: deploy
        depends_on:
            - database
        ports:
            - '${API_PORT}:${API_PORT}'
        volumes:
            - .:/app
            - /app/node_modules
volumes:
    data:
